name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - production # Changed from 'main' to 'production'
  pull_request:
    branches:
      - production # Trigger on pull requests targeting 'production' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Install slidev
        run: npm i -g @slidev/cli

      - name: playwright deps install
        run: npx playwright install-deps

      - name: Replace relative urls
        run: find . -type f \( -name "slide.md" -o -path "./components/*" -o -path "./pages/*" \) -exec sed -i 's,public/,https://maszz.github.io/sf407-slide/,g' {} +

      - name: Build
        run: npm run build -- --base /sf407-slide/

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
